CREATE TABLE poi (
    id BIGINT PRIMARY KEY,
    type ENUM('node', 'way', 'relation') NOT NULL,
    lat DOUBLE,
    lon DOUBLE,
    name VARCHAR(255),
    amenity VARCHAR(100),
    cuisine VARCHAR(255),
    phone VARCHAR(100),
    opening_hours VARCHAR(255),
    website VARCHAR(255),
    wheelchair VARCHAR(50),
    takeaway VARCHAR(50),
    delivery VARCHAR(50),
    smoking VARCHAR(50),
    outdoor_seating VARCHAR(50),
    reservation VARCHAR(100),
    addr_city VARCHAR(100),
    addr_country VARCHAR(10),
    addr_housenumber VARCHAR(20),
    addr_postcode VARCHAR(20),
    addr_street VARCHAR(255),
    tags JSON NOT NULL
) CHARACTER SET utf8mb4;

INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('332050722', 'node', '49.2479242', '7.3647348', 'Chin Chin Vietnamese Street Food', 'restaurant', 'vietnamese', '+49 6332 9066344', 'Mo-Su 11:00-22:00', NULL, 'yes', 'yes', 'no', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "vietnamese", "delivery": "no", "diet:vegetarian": "yes", "name": "Chin Chin Vietnamese Street Food", "opening_hours": "Mo-Su 11:00-22:00", "phone": "+49 6332 9066344", "takeaway": "yes", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('332251156', 'node', '49.2537675', '7.3446136', 'Dimi & Maxi', 'restaurant', 'greek', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "greek", "name": "Dimi & Maxi"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('334320901', 'node', '49.2501833', '7.3615583', 'Joni''s', 'restaurant', NULL, '+49 6332 9936883', 'Mo-Fr 09:30-22:00; Sa 09:30-23:30; Su 10:00-22:00; PH off', 'https://jonis-zweibruecken.eatbu.com', 'no', 'yes', 'no', 'outside', 'yes', 'recommended', 'Zweibrücken', 'DE', '98', '66482', 'Hauptstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "98", "addr:postcode": "66482", "addr:street": "Hauptstraße", "amenity": "restaurant", "delivery": "no", "diet:vegan": "yes", "diet:vegetarian": "yes", "name": "Joni''s", "opening_hours": "Mo-Fr 09:30-22:00; Sa 09:30-23:30; Su 10:00-22:00; PH off", "outdoor_seating": "yes", "payment:american_express": "no", "payment:cash": "yes", "payment:credit_cards": "yes", "payment:debit_cards": "yes", "payment:maestro": "yes", "payment:mastercard": "yes", "payment:notes": "no", "payment:telephone_cards": "no", "payment:visa": "yes", "phone": "+49 6332 9936883", "reservation": "recommended", "smoking": "outside", "takeaway": "yes", "website": "https://jonis-zweibruecken.eatbu.com", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('334329215', 'node', '49.2467024', '7.3610844', 'City Grill', 'fast_food', NULL, NULL, NULL, NULL, 'yes', 'only', NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "indoor_seating": "no", "name": "City Grill", "outdoor_seating": "no", "takeaway": "only", "toilets:wheelchair": "yes", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('336065215', 'node', '49.2471728', '7.3644619', 'Odysseus', 'restaurant', 'greek', '+49 6332 75243', NULL, NULL, 'limited', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "greek", "name": "Odysseus", "phone": "+49 6332 75243", "wheelchair": "limited"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('413928149', 'node', '49.2545619', '7.3492062', 'Ernstweilerhof', 'restaurant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Ernstweilerhof"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('433243542', 'node', '49.2337363', '7.360834', 'Eiscafé Maurer', 'cafe', NULL, NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "name": "Eiscafé Maurer", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('668735691', 'node', '49.2320192', '7.354864', 'China Restaurant China Town', 'restaurant', 'chinese', '+496332566188', NULL, NULL, 'limited', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "chinese", "name": "China Restaurant China Town", "phone": "+496332566188", "wheelchair": "limited"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('668786957', 'node', '49.2524877', '7.3751996', 'Restaurant Lichtergarten', 'restaurant', NULL, '+4963329770', NULL, 'https://www.rosengarten-am-park.com/', 'yes', NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '60', '66482', 'Rosengartenstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "60", "addr:postcode": "66482", "addr:street": "Rosengartenstraße", "amenity": "restaurant", "name": "Restaurant Lichtergarten", "phone": "+4963329770", "toilets:wheelchair": "yes", "website": "https://www.rosengarten-am-park.com/", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('684022140', 'node', '49.2549526', '7.3869107', 'Pizzeria "Da Salvatore"', 'restaurant', NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Pizzeria Da Salvatore", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('729600308', 'node', '49.2454817', '7.3719515', 'San Remo', 'restaurant', 'pizza', '+49 6332 75514', NULL, 'http://sanremo-zw.de/', 'no', NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '36', '66482', 'Himmelsbergstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "36", "addr:postcode": "66482", "addr:street": "Himmelsbergstraße", "amenity": "restaurant", "cuisine": "pizza", "description": "Pizzaria im Wohnviertel.", "name": "San Remo", "phone": "+49 6332 75514", "website": "http://sanremo-zw.de/", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('800603393', 'node', '49.250944', '7.416774', 'Hahnberghütte', 'restaurant', 'german', NULL, 'week 01-53/2 Su 10:00-18:00', 'https://www.pwv-zweibruecken.de/html/huette.html', NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "german", "name": "Hahnberghütte", "opening_hours": "week 01-53/2 Su 10:00-18:00", "operator": "Pfälzerwald-Verein OG Zweibrücken", "outdoor_seating": "yes", "website": "https://www.pwv-zweibruecken.de/html/huette.html"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('933057175', 'node', '49.2602488', '7.3612799', 'Mensa Hochschule', 'restaurant', NULL, NULL, 'Mo-Fr 11:15-14:00', 'https://www.studierendenwerk-kaiserslautern.de/', 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Mensa Hochschule", "opening_hours": "Mo-Fr 11:15-14:00", "website": "https://www.studierendenwerk-kaiserslautern.de/", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('937869520', 'node', '49.2572698', '7.3599877', 'Hostaria La Romantica', 'restaurant', 'italian', NULL, 'closed "Restaurant geschlossen."', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '95', '66482', 'Landstuhler Straße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "95", "addr:postcode": "66482", "addr:street": "Landstuhler Straße", "amenity": "restaurant", "cuisine": "italian", "name": "Hostaria La Romantica", "opening_hours": "closed"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('1147280365', 'node', '49.2564739', '7.3928144', 'Alte Brauerei Grund', 'restaurant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Alte Brauerei Grund"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('1152859123', 'node', '49.2559929', '7.378253', 'Sportheim', 'restaurant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Sportheim"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('1279060180', 'node', '49.2349847', '7.3566236', 'Zur Breitwiese', 'restaurant', 'italian', NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "italian", "name": "Zur Breitwiese", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('1363057445', 'node', '49.2297023', '7.4014643', 'Terra', 'restaurant', NULL, '+49 6332 48179-70', 'Mo-Su 11:30-14:00,17:30-23:00', 'https://www.wof-zw.de/terra/php/index.php', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Terra", "opening_hours": "Mo-Su 11:30-14:00,17:30-23:00", "phone": "+49 6332 48179-70", "website": "https://www.wof-zw.de/terra/php/index.php"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('1473293724', 'node', '49.2312715', '7.3599909', 'Pizzeria La Bandiera', 'restaurant', 'italian', NULL, 'Mo-Su 17:00-22:00, Fr,Su 11:00-13:30; Tu off', 'https://www.la-bandiera-zw.de/', NULL, NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '92', '66482', 'Bitscher Straße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "92", "addr:postcode": "66482", "addr:street": "Bitscher Straße", "amenity": "restaurant", "check_date:opening_hours": "2021-06-16", "cuisine": "italian", "internet_access": "wlan", "internet_access:fee": "customers", "name": "Pizzeria La Bandiera", "opening_hours": "Mo-Su 17:00-22:00, Fr,Su 11:00-13:30; Tu off", "payment:cash": "yes", "payment:credit_cards": "no", "payment:debit_cards": "no", "website": "https://www.la-bandiera-zw.de/"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('2156402225', 'node', '49.2456621', '7.3651317', 'Urfa Kebab Haus', 'restaurant', 'pizza;kebab', NULL, NULL, NULL, 'yes', NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "pizza;kebab", "name": "Urfa Kebab Haus", "outdoor_seating": "no", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('2209576537', 'node', '49.2467856', '7.3650158', 'Pizza Per Tutti', 'restaurant', 'italian', NULL, 'Mo-Sa 11:30-14:30,17:30-23:30; Tu 17:30-23:30; Su 12:30-22:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "contact:phone": "+49 6332 75574", "contact:website": "http://pizzapertutti-zw.de", "cuisine": "italian", "lastcheck": "2017-07-26", "name": "Pizza Per Tutti", "opening_hours": "Mo-Sa 11:30-14:30,17:30-23:30; Tu 17:30-23:30; Su 12:30-22:00"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('2255854800', 'node', '49.2298542', '7.3644718', 'Krummackerhütte', 'restaurant', 'regional', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '90', '66482', 'Am Krummacker', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "90", "addr:postcode": "66482", "addr:street": "Am Krummacker", "amenity": "restaurant", "cuisine": "regional", "name": "Krummackerhütte"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('2282338093', 'node', '49.2561892', '7.3885475', 'Auerbacher Hof', 'restaurant', 'german', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "german", "name": "Auerbacher Hof"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('3088868516', 'node', '49.2503761', '7.362776', 'World Foot Trip', 'restaurant', NULL, '+49 176 76682115', 'Mo-Fr 11:00-20:00; Sa 12:00-20:00; Su off; PH off', 'https://worldfoodtrip.de', 'limited', 'only', 'no', 'outside', 'yes', 'no', 'Zweibrücken', 'DE', '5a', '66482', 'Rosengartenstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "5a", "addr:postcode": "66482", "addr:street": "Rosengartenstraße", "amenity": "restaurant", "delivery": "no", "diet:vegan": "yes", "diet:vegetarian": "yes", "internet_access": "no", "microbrewery": "no", "name": "World Foot Trip", "opening_hours": "Mo-Fr 11:00-20:00; Sa 12:00-20:00; Su off; PH off", "outdoor_seating": "yes", "phone": "+49 176 76682115", "reservation": "no", "smoking": "outside", "takeaway": "only", "website": "https://worldfoodtrip.de", "wheelchair": "limited"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('3110038842', 'node', '49.2540238', '7.365468', 'Thai Chi', 'restaurant', 'asian', NULL, 'Mo-Sa 10:30-22:30; Su,PH 12:00-22:00', NULL, 'yes', NULL, 'yes', 'no', NULL, NULL, 'Zweibrücken', 'DE', '37', '66482', 'Saarlandstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "37", "addr:postcode": "66482", "addr:street": "Saarlandstraße", "amenity": "restaurant", "contact:phone": "+49 6332 9072350", "cuisine": "asian", "delivery": "yes", "name": "Thai Chi", "opening_hours": "Mo-Sa 10:30-22:30; Su,PH 12:00-22:00", "smoking": "no", "toilets:wheelchair": "yes", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('3188600462', 'node', '49.2527132', '7.3498268', 'Beisl', 'restaurant', NULL, NULL, 'Mo-Th 17:00-23:00; Fr-Sa 17:00-24:00; Su 17:00-22:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "contact:facebook": "https://www.facebook.com/zumbeisl/", "contact:phone": "+49 6332 905090", "contact:website": "http://www.beisl.de/", "name": "Beisl", "opening_hours": "Mo-Th 17:00-23:00; Fr-Sa 17:00-24:00; Su 17:00-22:00"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('3347609094', 'node', '49.2512006', '7.3436565', 'Restaurant Toscana', 'restaurant', 'bistro', NULL, 'Mo-Fr 10:00-20:00; Sa 09:30-20:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '3', '66482', 'Wilkstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "3", "addr:postcode": "66482", "addr:street": "Wilkstraße", "amenity": "restaurant", "contact:website": "http://www.moebel-martin.de/zweibruecken/248.htm", "cuisine": "bistro", "level": "2", "name": "Restaurant Toscana", "opening_hours": "Mo-Fr 10:00-20:00; Sa 09:30-20:00"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('4424547424', 'node', '49.2668185', '7.3221349', 'Saigon', 'restaurant', 'vietnamese', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "vietnamese", "name": "Saigon"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('5395641128', 'node', '49.2320929', '7.3708716', 'Café Kurt Rücker', 'cafe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "name": "Café Kurt Rücker"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('5876263457', 'node', '49.2448121', '7.3649981', 'Phils Pizza Und Pasta', 'restaurant', 'italian', '+49 6332 9066680', 'Tu-Su 15:00-22:00', 'https://philspizza.de/', NULL, 'yes', 'yes', NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "italian", "delivery": "yes", "name": "Phils Pizza Und Pasta", "opening_hours": "Tu-Su 15:00-22:00", "outdoor_seating": "no", "phone": "+49 6332 9066680", "takeaway": "yes", "website": "https://philspizza.de/"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('5876263460', 'node', '49.2477726', '7.3663776', 'Portofino', 'restaurant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Portofino", "outdoor_seating": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('5876263461', 'node', '49.2468583', '7.3650802', 'Orient Grill', 'restaurant', 'kebab', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "kebab", "name": "Orient Grill"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('6239400085', 'node', '49.2483261', '7.3515196', 'Subway', 'fast_food', 'sandwich', NULL, 'Mo 10:00-23:00; Tu-Fr 09:00-23:00; Sa-Su 09:00-24:00', NULL, 'yes', 'yes', NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "brand": "Subway", "brand:wikidata": "Q244457", "brand:wikipedia": "en:Subway (restaurant)", "check_date": "2024-05-12", "contact:phone": "+49 6332 8076373", "contact:website": "https://www.subway.com/de-DE/FindAStore?zip=zweibr%C3%BCcken", "cuisine": "sandwich", "name": "Subway", "opening_hours": "Mo 10:00-23:00; Tu-Fr 09:00-23:00; Sa-Su 09:00-24:00", "ref": "58976", "smoking": "no", "takeaway": "yes", "toilets": "yes", "toilets:access": "customers", "toilets:wheelchair": "yes", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('6265530931', 'node', '49.2474602', '7.3581332', 'Gleis 3', 'restaurant', NULL, NULL, 'Mo-Th 18:00-22:00; Fr,Sa 18:00-23:00', NULL, 'yes', NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "diet:vegetarian": "no", "indoor_seating": "yes", "name": "Gleis 3", "opening_hours": "Mo-Th 18:00-22:00; Fr,Sa 18:00-23:00", "opening_hours:signed": "no", "outdoor_seating": "no", "toilets:wheelchair": "yes", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('6832380031', 'node', '49.2676317', '7.321528', 'Efes', 'fast_food', 'kebab;pizza', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "cuisine": "kebab;pizza", "name": "Efes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('6832626779', 'node', '49.2665256', '7.3237167', 'Amici-Mici', 'fast_food', 'pizza', NULL, NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "cuisine": "pizza", "delivery": "yes", "name": "Amici-Mici"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('7264649164', 'node', '49.2494172', '7.3618889', 'Asia Gourmet Mikado Sushibar', 'restaurant', 'asian', '+49 6332 5669400', 'Mo off; Tu-Su 11:30-21:30; PH off', 'https://asia-gourmet-mikado-zweibruecken.business.site/', NULL, 'yes', 'no', NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "asian", "delivery": "no", "indoor_seating": "yes", "name": "Asia Gourmet Mikado Sushibar", "opening_hours": "Mo off; Tu-Su 11:30-21:30; PH off", "outdoor_seating": "yes", "phone": "+49 6332 5669400", "takeaway": "yes", "website": "https://asia-gourmet-mikado-zweibruecken.business.site/"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8532643407', 'node', '49.2302572', '7.4049767', 'Starbucks', 'cafe', 'coffee_shop', NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "brand": "Starbucks", "brand:wikidata": "Q37158", "brand:wikipedia": "en:Starbucks", "cuisine": "coffee_shop", "name": "Starbucks", "official_name": "Starbucks Coffee", "takeaway": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8972679213', 'node', '49.2485107', '7.3636924', 'Café am Schloss', 'cafe', NULL, '+49 6332 73155', 'Mo-Fr 07:30-18:00; Sa 07:30-14:00; Su 13:00-18:00; PH off', NULL, NULL, 'yes', NULL, NULL, 'yes', NULL, 'Zweibrücken', 'DE', '5', '66482', 'Schlossplatz', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "5", "addr:postcode": "66482", "addr:street": "Schlossplatz", "amenity": "cafe", "name": "Café am Schloss", "opening_hours": "Mo-Fr 07:30-18:00; Sa 07:30-14:00; Su 13:00-18:00; PH off", "outdoor_seating": "yes", "phone": "+49 6332 73155", "takeaway": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8977116776', 'node', '49.2473657', '7.3652335', 'Schnellimbiss Grimm', 'fast_food', 'burger', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "cuisine": "burger", "name": "Schnellimbiss Grimm"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8977125511', 'node', '49.2513347', '7.3762203', 'Am Storchennest', 'restaurant', 'regional', NULL, NULL, NULL, 'no', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "regional", "name": "Am Storchennest", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8977175034', 'node', '49.2525969', '7.3771157', 'Pommesbude', 'fast_food', 'german', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"access": "customers", "amenity": "fast_food", "cuisine": "german", "name": "Pommesbude", "note": "Zugang nur für Schwimmbad-Besucher"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('8997232758', 'node', '49.2442164', '7.3846209', 'Udo‘ Snack Bar', 'restaurant', NULL, '+49 6332 4605775', 'Mo-Sa 07:00-20:00', NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "diet:vegetarian": "yes", "name": "Udo‘ Snack Bar", "opening_hours": "Mo-Sa 07:00-20:00", "phone": "+49 6332 4605775", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9383923863', 'node', '49.2578851', '7.3821165', 'Asia Garden', 'restaurant', 'chinese', NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "chinese", "diet:vegetarian": "yes", "internet_access": "no", "microbrewery": "no", "name": "Asia Garden", "takeaway": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9395274845', 'node', '49.2490068', '7.36316', 'Ikigai Restaurant', 'restaurant', 'asian', '+49 6332 9068060', NULL, 'https://flipsnack.com/', 'yes', 'yes', 'no', 'outside', 'yes', 'recommended', NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "capacity": "50", "cuisine": "asian", "delivery": "no", "name": "Ikigai Restaurant", "outdoor_seating": "yes", "phone": "+49 6332 9068060", "reservation": "recommended", "smoking": "outside", "takeaway": "yes", "website": "https://flipsnack.com/", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9402206189', 'node', '49.2475566', '7.3638251', 'Cafe Leiner', 'cafe', 'coffee_shop', NULL, 'Mo-Fr 07:00-18:00; Sa 07:00-14:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "cuisine": "coffee_shop", "diet:vegan": "yes", "diet:vegetarian": "yes", "name": "Cafe Leiner", "opening_hours": "Mo-Fr 07:00-18:00; Sa 07:00-14:00", "shop": "bakery"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9403160211', 'node', '49.2457978', '7.3653097', 'My Sushi', 'restaurant', 'sushi', '+49 6332 8737475', 'Tu-Su 17:00-22:00', NULL, NULL, 'yes', 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "sushi", "delivery": "yes", "diet:vegetarian": "yes", "name": "My Sushi", "opening_hours": "Tu-Su 17:00-22:00", "phone": "+49 6332 8737475", "takeaway": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9405090759', 'node', '49.2489661', '7.3774441', 'Gondoliere', 'restaurant', 'pizza', '+49 6332 72211', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "pizza", "name": "Gondoliere", "phone": "+49 6332 72211"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9441814687', 'node', '49.2450615', '7.3637205', 'Always Fresh', 'fast_food', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "name": "Always Fresh"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9464323047', 'node', '49.2446045', '7.3561218', 'Il Dolce Freddo', 'cafe', 'ice_cream', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "cuisine": "ice_cream", "name": "Il Dolce Freddo"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9997753152', 'node', '49.2387776', '7.3716733', 'Pfälzer Hof', 'restaurant', 'german', '+49 6332 905008', 'Mo-Fr,Su,PH 11:30-14:00,17:30-24:00; Sa 17:30-24:00', 'http://www.pfaelzerhof-zweibruecken.de', 'no', NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', 'DE', '92', '66482', 'Oselbachstraße', '{"addr:city": "Zweibrücken", "addr:country": "DE", "addr:housenumber": "92", "addr:postcode": "66482", "addr:street": "Oselbachstraße", "amenity": "restaurant", "cuisine": "german", "email": "pfaelzerhof-zw@gmx.de", "name": "Pfälzer Hof", "opening_hours": "Mo-Fr,Su,PH 11:30-14:00,17:30-24:00; Sa 17:30-24:00", "payment:cash": "yes", "payment:mastercard": "yes", "payment:visa": "yes", "phone": "+49 6332 905008", "tenant": "Heidi Marschall", "website": "http://www.pfaelzerhof-zweibruecken.de", "wheelchair": "no"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('9998273497', 'node', '49.234683', '7.3618852', 'Zum Roten Ochsen', 'restaurant', 'german', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "cuisine": "german", "name": "Zum Roten Ochsen"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('10753058659', 'node', '49.2246708', '7.3999563', 'Trattoria la Calabria', 'restaurant', 'italian;pizza;pasta', '+4963329935299', 'Mo off; Tu 17:30-22:00; We-Fr 11:30-14:00,17:30-22:00; Sa 17:30-22:00; Su 11:30-14:00,17:30-22:00', 'https://trattoria-la-calabria-zweibruecken.eatbu.com', 'yes', 'yes', 'yes', NULL, NULL, NULL, 'Zweibrücken', NULL, '21', '66482', 'Straßburger Ring', '{"addr:city": "Zweibrücken", "addr:housenumber": "21", "addr:postcode": "66482", "addr:street": "Straßburger Ring", "amenity": "restaurant", "cuisine": "italian;pizza;pasta", "delivery": "yes", "dog": "yes", "name": "Trattoria la Calabria", "opening_hours": "Mo off; Tu 17:30-22:00; We-Fr 11:30-14:00,17:30-22:00; Sa 17:30-22:00; Su 11:30-14:00,17:30-22:00", "pets_allowed": "yes", "phone": "+4963329935299", "takeaway": "yes", "website": "https://trattoria-la-calabria-zweibruecken.eatbu.com", "wheelchair": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('11046943605', 'node', '49.2476432', '7.3636945', 'Akifs Bistro', 'restaurant', 'turkish;pizza;kebab;pasta', '+4963329059737', 'Mo-Sa 11:00-22:00; Su 13:00-22:00', 'https://akifs-bistro.eatbu.com/', 'limited', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '66482', NULL, '{"addr:postcode": "66482", "amenity": "restaurant", "cuisine": "turkish;pizza;kebab;pasta", "name": "Akifs Bistro", "opening_hours": "Mo-Sa 11:00-22:00; Su 13:00-22:00", "phone": "+4963329059737", "website": "https://akifs-bistro.eatbu.com/", "wheelchair": "limited"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('11271415410', 'node', '49.2373643', '7.4137142', 'Truppacher Hof', 'restaurant', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "restaurant", "name": "Truppacher Hof", "outdoor_seating": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('11805031097', 'node', '49.2540635', '7.3440452', 'Vitamin Küche', 'fast_food', 'kebab;pizza', NULL, 'Th-Tu 13:00-21:45', 'https://www.vitaminkueche-zweibruecken.de/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "cuisine": "kebab;pizza", "drive_through": "no", "level": "0", "name": "Vitamin Küche", "opening_hours": "Th-Tu 13:00-21:45", "website": "https://www.vitaminkueche-zweibruecken.de/"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('12098336728', 'node', '49.2298753', '7.4088594', 'McDonald''s', 'fast_food', 'burger', NULL, NULL, NULL, NULL, 'yes', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "fast_food", "brand": "McDonald''s", "cuisine": "burger", "fixme": "Details hinzufügen, wenn Satellitenbilder verfügbar", "name": "McDonald''s", "takeaway": "yes"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('13059473975', 'node', '49.2518696', '7.3739061', 'Dornröschen', 'cafe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"amenity": "cafe", "name": "Dornröschen"}');
INSERT INTO poi (id, type, lat, lon, name, amenity, cuisine, phone, opening_hours, website, wheelchair, takeaway, delivery, smoking, outdoor_seating, reservation, addr_city, addr_country, addr_housenumber, addr_postcode, addr_street, tags) VALUES ('13061458466', 'node', '49.2297286', '7.4061413', 'Sushi Tomo', 'restaurant', NULL, '+4963324729149', 'Mo-Sa 11:00-19:30', 'https://sushitomo.smoothr.de/home', NULL, NULL, NULL, NULL, NULL, NULL, 'Zweibrücken', NULL, '94b', '66482', 'Londoner Bogen', '{"addr:city": "Zweibrücken", "addr:housenumber": "94b", "addr:postcode": "66482", "addr:street": "Londoner Bogen", "air_conditioning": "yes", "amenity": "restaurant", "check_date": "2025-08-09", "check_date:currency:XBT": "2025-08-09", "currency:XBT": "yes", "diet:fish": "yes", "diet:vegan": "yes", "diet:vegetarian": "yes", "name": "Sushi Tomo", "opening_hours": "Mo-Sa 11:00-19:30", "payment:cash": "yes", "payment:credit_cards": "yes", "payment:debit_cards": "yes", "payment:lightning": "yes", "payment:lightning_contactless": "no", "payment:onchain": "no", "phone": "+4963324729149", "survey:date": "2025-08-09", "website": "https://sushitomo.smoothr.de/home"}');